### PR TITLE
more automation

### PR DESCRIPTION
**Pull request by daviddalpiaz**
- import R.utils
- "autoloader" function
- consistent assignment operator
- remove 2nd license

### CODE REVIEW

**Comment by daviddalpiaz** [comment]
Also, I'm not sure how `README.md` is being automatically generated. I only edited the `.Rmd` which had no effect on the `.md`.

**Comment by bryonaragam** [comment]
Looks good! Only change I suggest is to avoid using global variables, and instead have autoloadMNIST return a list ([as loadMNIST does](https://github.com/itsrainingdata/mnistR/blob/63985f9503ec581a98ee46007c9e7cb1bcb02029/R/mnistR-data.R#L18)).

**Comment by daviddalpiaz** [comment]
Yeah, I agree, that was just a quick hack to make it work with existing functions.

Maybe we should split up the load function into a train and test function, then have two autoload functions. So once installed, you could simply run two lines of code two have two data frames ready to use, instead of needing to manually split up the list:

```
mnist_trn = autoload_mnist_trn()
mnist_tst = autoload_mnist_tst()
```

**Comment by bryonaragam** [comment]
This seems largely the same as the list strategy, with the added cost of two function calls vs one. In my experience, returning a list is fairly idiomatic R (an S3 object would be the most idiomatic, but seems overkill). Any reason for avoiding this? (Always trying to improve my coding chops so thoughts welcome.)

Another option: Just return all 60k rows in one data.frame.

**Comment by bryonaragam** [comment]
Alternatively, we could add an argument to autoloadMNIST specifying whether to return train, test, or both 😜

**Comment by daviddalpiaz** [comment]
My understanding is that having a function return a list is pretty idiomatic `R`, but from the perspective of modeling the data, I'd want train and test sets as separate data frames. That way you can start modeling right away with any function that uses formula syntax:

```
fit = some_ml_method(y ~ ., data = mnist_trn)
```

It's really a minor point though, since as is, you could just do:

```
fit = some_ml_method(y ~ ., data = mnist$train)
```

I sort of just don't like the way that looks. :)

I like your suggestion since it fits in with the whole idea of "tidy" data, but that would probably lead to people creating their own test-train split, which sort of defeats the purpose of MNIST, since there is basically a long running leaderboard on that test set.

**Comment by daviddalpiaz** [comment]
Oh, that would be nice, but is there an easy way to do that without using global assignment?

**Comment by coatless** [comment]
Jumping in here as I just spoke with @daviddalpiaz 

Given the compartmentalization of the functions, it would be better to create two distinct functions that respectively load data frames containing only training and test data.

e.g. 

```r
train_mnist = mnistr::load_training_mnist(dest = "/path/to/")
test_mnist = mnistr::load_testing_mnist(dest = "/path/to/")
```

You could go the approach of adding a filter within the:

```r 
mnistr::load_mnist(dest = "/path/to/", dataset = c("all", "train", "test"))

```

Going this route would likely elicit confusion as it introduces return ambiguity of observations/columns depending on call. For example, what data was loaded via `mnistr::load_mnist` the train, test, or both? In turn, this would also lead to the need to add a column that labels the data list (e.g. Set: `train` or `test`).

**Comment by bryonaragam** [comment]
Splitting into two separate methods (6 total with download / load / autoload) is fine with me. We can also maintain the current down/loadMNIST style by simply wrapping around these methods.

Probably makes sense to remove the autoload method from this PR, and move that into another PR. I'm fine either way though - the other changes look good!

**Comment by daviddalpiaz** [comment]
Added commits which implement the six function approach. (And also remove previous "autoload" function.)

**Comment by bryonaragam** [comment]
Merged and closed. I re-implemented the (down)loadMNIST methods to remain compatible with the original methods.

**Pull request merged**
